# Generated by Django 4.0.5 on 2022-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_name_az_tag_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
