# Generated by Django 4.0.5 on 2022-11-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='is_main',
        ),
    ]
