# Generated by Django 4.0.5 on 2022-12-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_cart_owner_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
