# Generated by Django 4.0.5 on 2022-12-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
