# Generated by Django 4.0.5 on 2022-12-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_order_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(default='PayPal', max_length=100),
        ),
    ]
