# Generated by Django 4.0.5 on 2022-09-23 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='sdfsdf', max_length=100, null=True)),
                ('name_az', models.CharField(blank=True, default='sdfsdf', max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, default='sdfsdf', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('activated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=200, null=True)),
                ('resolution', models.CharField(max_length=200, null=True)),
                ('color_settings', models.CharField(max_length=255, null=True)),
                ('touch', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('operating_system', models.CharField(max_length=150, null=True)),
                ('processor', models.TextField(blank=True, null=True)),
                ('processor_tech', models.TextField(blank=True, null=True)),
                ('graphics', models.TextField(blank=True, null=True)),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('hard_drive', models.TextField(blank=True, null=True)),
                ('power_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('battery', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=128), default=list, size=None)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Wireless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.CharField(max_length=255, null=True)),
                ('bluetooth', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
