# Generated by Django 4.0.5 on 2022-10-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_screen_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
