# Generated by Django 4.0.5 on 2022-11-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_screen_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='is_main',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
