# Generated by Django 4.0.5 on 2022-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
