# Generated by Django 4.0.5 on 2022-11-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_campaign_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='extra_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
