# Generated by Django 4.0.5 on 2022-11-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_campaign_extra_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
