# Generated by Django 4.0.5 on 2022-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_tag_name_az_tag_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.screen'),
        ),
    ]
