# Generated by Django 4.0.5 on 2022-12-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_product_operating_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
