# Generated by Django 4.0.5 on 2022-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
